apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-pi"
  namespace: spark-app
spec:
  timeToLiveSeconds: 3600
  type: Scala
  mode: cluster
  image: apache/spark:v3.3.1
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local://///opt/spark/examples/jars/spark-examples_2.12-3.3.1.jar"
  sparkConf:
    spark.kubernetes.authenticate.driver.serviceAccountName: spark
  sparkVersion: 3.0.0
  driver:
    memory: 1G
  executor:
    instances: 1
    cores: 1
    memory: 1G
